package com.microsys.poc.jni.entity.type;

/**
消息类型 
ADDRESSBOOK	代表通讯录 
SELFINFO	代表本地信息 
SIPMSG		代表sip消息
TBCPMSG		代表tbcp消息
TEXTMSG		代表微信消息
USERSTATE	代表用户状态
*/
public enum CallBackInfoType {
	ADDRESSBOOK,
	SELFINFO,
	SIPMSG,
	TBCPMSG,
	TEXTMSG,
	USERSTATE,
	RESOLUTION,
	USERTWOLOADING,
	LOCALMEDIAPOWER,
	VERSIONUPDATE,
	TEMPGROUPSUC,
	RESETPWDSUC,//重置密码
	GROUPLISTENSTATE,//组呼监听
	SKTINFO,
	USERTYPEINFO,
	CALLTYPECHANGE,
	ESIPHEADNUM,  //esip字冠
	SYNGROUPLISTENSTATE,
	ADDRESSURL,
	MEETING_USERS_ON_CALL_CHANGE

}
